# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/the-snake-project',
                'doc_host': 'https://jimmiemunyi.github.io',
                'git_url': 'https://github.com/jimmiemunyi/the-snake-project',
                'lib_path': 'the_snake_project'},
  'syms': { 'the_snake_project.core': { 'the_snake_project.core.get_dls': ('core.html#get_dls', 'the_snake_project/core.py'),
                                        'the_snake_project.core.get_species': ('core.html#get_species', 'the_snake_project/core.py'),
                                        'the_snake_project.core.get_x': ('core.html#get_x', 'the_snake_project/core.py'),
                                        'the_snake_project.core.get_y_gns': ('core.html#get_y_gns', 'the_snake_project/core.py')}}}
