# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/the-snake-project',
                'doc_host': 'https://jimmiemunyi.github.io',
                'git_url': 'https://github.com/jimmiemunyi/the-snake-project',
                'lib_path': 'the_snake_project'},
  'syms': {'the_snake_project.core': {'the_snake_project.core.get_species': ('core.html#get_species', 'the_snake_project/core.py')}}}
