# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['ds_path', 'ds', 'get_species', 'get_x', 'get_y_gns', 'get_dls']

# %% ../nbs/00_core.ipynb 5
from pandas import Series
from fastcore.xtras import Path
from fastai.vision.data import ImageBlock, CategoryBlock
from fastai.data.block import DataBlock
from fastai.data.transforms import RandomSplitter

# %% ../nbs/00_core.ipynb 8
ds_path = '../../dataset/ai-crowd-snake-dataset/'

# %% ../nbs/00_core.ipynb 9
ds = Path(ds_path)
Path.BASE_PATH = ds

# %% ../nbs/00_core.ipynb 12
def get_species(
        row # pandas dataframe row.
    )->Series: # pandas dataframe series
    """Add a species column in the series"""
    _, species = row.binomial.split()
    return species

# %% ../nbs/00_core.ipynb 13
def get_x(r):
    """Returns the image path"""
    p1, p2, nm = r['image_path'].split('/')[-3:]
    return ds/'training_data'/p1/p2/nm
    # return f'{p1}/{p2}/{nm}'

# %% ../nbs/00_core.ipynb 14
def get_y_gns(r):
    """Get the label y - Only the genus"""
    return r.genus

# %% ../nbs/00_core.ipynb 15
def get_dls(df, get_x, get_y, item_tfms, batch_tfms=None):
    dblock = DataBlock(
        blocks=(ImageBlock, CategoryBlock),
        get_x=get_x,
        get_y=get_y,
        splitter=RandomSplitter(valid_pct=0.2),
        item_tfms=item_tfms,
        batch_tfms=batch_tfms
    )
    
    return dblock.dataloaders(df)
